[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
authors = ["cSky-oss"]

[build-dependencies]
cfgrammar = "0.13"
pest = "2.7.15"
lrlex = "0.11.0"

[dependencies]
cfgrammar = "0.13"
pest = "2.7.15"
pest_derive = "2.5.6"